name: DBNet
arch:
  type: Model
  backbone:
    type: resnet50
    pretrained: true
    in_channels: 3
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  CUDA_VISIBLE_DEVICES: 0
  seed: 2
  epochs: 200
  log_iter: 1
  show_images_iter: 1
  resume_checkpoint: ''
  output_dir: output
dataset:
  train:
    dataset:
      args:
        pre_processes:
          - type: IaaAugment
            args:
              - { 'type': Fliplr, 'args': { 'p': 0.5 } }
              - { 'type': Affine, 'args': { 'rotate': [ -10,10 ] } }
              - { 'type': Resize,'args': { 'size': [ 0.5,3 ] } }
          - type: EastRandomCropData
            args:
              size: [ 640,640 ]
              max_tries: 50
              keep_ratio: true
          - type: MakeBorderMap
            args:
              shrink_ratio: 0.4
              thresh_min: 0.3
              thresh_max: 0.7
          - type: MakeShrinkMap
            args:
              shrink_ratio: 0.4
              min_text_size: 8
        data_path:
          - D:/develop/dataset/ICDAR2017RCTW/train.json
        transforms:
          - type: ToTensor
            args: {}
          - type: Normalize
            args:
              mean: [0.462, 0.450, 0.440]
              std: [0.271, 0.270, 0.274]
        img_mode: RGB
        load_char_annotation: false
        expand_one_char: false
        filter_keys: [ img_path,img_name,text_polys,texts,ignore_tags,shape ] # 返回数据之前，从数据字典里删除的key
        ignore_tags: [ '*', '###' ]
    loader:
      batch_size: 21
      shuffle: true
      pin_memory: true
      num_workers: 2
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - D:/develop/dataset/ICDAR2017RCTW/test.json
        transforms:
          - type: ToTensor
            args: { }
          - type: Normalize
            args:
              mean: [0.462, 0.450, 0.440]
              std: [0.271, 0.270, 0.274]
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 640
              resize_text_polys: false
        img_mode: RGB
        load_char_annotation: false # 是否加载字符级标注
        expand_one_char: false # 是否对只有一个字符的框进行宽度扩充，扩充后w = w+h
        filter_keys: []
        ignore_tags: [ '*', '###' ]
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 4
      collate_fn: ICDARCollectFN
